language: node_js
cache: 
  directories:
    - !@/.npm
node_js: 
  - '9'
git:
  depth: 3
script:
  - yarn build
branches:
  only:
    - develop
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $github_token
  local-dir: dist/
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on: 
    branch: master